[toolchain]
anchor_version = "0.29.0"
solana_version = "2.0.19"

[features]
seeds = false
skip-lint = false

[programs.localnet]
midan = "4VmPGCKEvpw4cLPrKTWAXozs5SBinUHWxmiK3cQdUaQ1"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/bilalafzal/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
